name: Build
on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ '**' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 2.12, 2.13 ]
        java:
          - adopt@1.8
        platform: [ jvm ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@744e9ce1e30f404577342a2e2abc30c3023c380a # v12
        with:
          java-version: ${{ matrix.java }}

      - name: Set up Aerospike Database
        uses: reugn/github-action-aerospike@2065a9209cfd5ef88a3e07f3e7929e321d1e0067 # v1.1.0

      - name: Cache sbt
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Build and test
        run: sbt ++${{ matrix.scala }} test